### ISSUE TITLE
0*C reading on Radeon R9 390

### ISSUE THREAD

**Issue by djseban** [RehabMan/OS-X-FakeSMC-kozlek#6]
Hi,

I just installed version 1530 of FakeSMC from your fork and came across bug similar to all FakeSMC versions (this bug exists also in kozlek's FakeSMC). The thing is on Radeon R9 290, R9 290X, R9 390 and R9 390X (I don't know if it applies to all variants of these GPUs) RadeonSensors is reporting improper temperature reading: 0*C (look "Grafika" section). Screen:
![zrzut ekranu 2016-03-05 o 20 24 07](https://cloud.githubusercontent.com/assets/6154527/13549877/3e4d9b26-e310-11e5-9258-717667effe65.png)
Is there any way to fix it?

**Comment by RehabMan** [comment]
I have no Radeon hardware.  Note that the current FakeSMC in my fork is 1707.

**Comment by lahdekorpi** [comment]
I'd like to have a shot at this. Would you have any ideas on where to start as a beginner? Any suggestions on how you usually look for the correct addresses for the data?
Would looking at the `xserver-xorg-video-ati` drivers be a good start since they do support temperature reading via lm-sensors?

Thanks!

**Comment by djseban** [comment]
@lahdekorpi Try to install the newest rev of FakeSMC, as I recall this issue is fixed.

**Comment by lahdekorpi** [comment]
@djseban thanks! I'm using the pre-built "RehabMan-FakeSMC-2018-0915"
Looking at this repo, the latest changes should be there? Or is there a fork?
